### ISSUE TITLE
Kiai.js v1.1.5 does not work with CommonJS

### ISSUE THREAD

**Issue by OIRNOIR** [buape/utilities#118]
Kiai.js v1.1.5 errors on using CommonJS. This should be fixed to support CommonJS codebases.

**Comment by OIRNOIR** [comment]
It seems that this is because you are using v3 of node-fetch instead of v2, the former of which does not support CommonJS. I'll address this with a PR

**Comment by thewilloftheshadow** [comment]
Fixed with #120
